name: awesome_emojis
description: Awesome Emojis for Dart!
version: 0.1.0
homepage:  https://github.com/daviresio/awesome_emojis

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.10.0
